### ISSUE TITLE
datree test json,xml and yaml output change on version 1.0.0

### ISSUE THREAD

**Issue by TzlilSwimmer123** [SuyashSonawane/vscode-datree#3]
Hi,
datree version 1.0.0 contains an update to the `datree test`  json, xml and yaml output. We added `occurrences` property to the `occurrencesDetails` object

**Comment by eyarz** [comment]
here is an example:
```yaml
  - identifier: CONTAINERS_MISSING_CPU_LIMIT_KEY
    name: Ensure each container has a configured CPU limit
    messageOnFailure: Missing property object `limits.cpu` - value should be within
      the accepted boundaries recommended by the organization
    occurrencesDetails:
    - metadataName: release-name-prometheus-node-exporter
      kind: DaemonSet
      occurrences: 1
    - metadataName: release-name-prometheus-alertmanager
      kind: Deployment
      occurrences: 2
```
